import React from 'react'
import { useNavigate } from 'react-router-dom'

const PrivacyPolicy = () => {
  const navigate = useNavigate()

  const handleBack = () => {
    navigate(-1)
  }

  return (
    <div className="min-h-screen bg-matka-grey-900">
      {/* Header */}
      <div className="bg-matka-green-800 shadow-lg px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <button
              onClick={handleBack}
              className="p-2 rounded-md text-white hover:bg-matka-green-700 transition-colors duration-200"
            >
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
            </button>
            <h1 className="text-xl font-bold text-white">Privacy Policy</h1>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="p-4 lg:p-6 bg-matka-grey-800 min-h-screen">
        <div className="max-w-4xl mx-auto">
          <div className="bg-gray-800 rounded-lg shadow-md p-6 lg:p-8 border border-gray-700">
            <div className="prose prose-invert max-w-none">
              <h2 className="text-2xl font-bold text-white mb-6">Privacy Policy for Raj Kalyan Matka</h2>
              
              <div className="text-gray-300 mb-6">
                <p className="text-sm text-gray-400">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
              </div>

              <div className="space-y-6 text-gray-300">
                <p>
                  This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>

                <p>
                  We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>

                <h3 className="text-xl font-semibold text-white mt-8 mb-4">Interpretation and Definitions</h3>
                
                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Interpretation</h4>
                <p>
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Definitions</h4>
                <p>For the purposes of this Privacy Policy:</p>
                
                <ul className="list-disc pl-6 space-y-2 mt-4">
                  <li><strong className="text-white">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                  <li><strong className="text-white">Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                  <li><strong className="text-white">Application</strong> refers to Raj Kalyan Matka, the software program provided by the Company.</li>
                  <li><strong className="text-white">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Raj Kalyan Matka.</li>
                  <li><strong className="text-white">Country</strong> refers to: India</li>
                  <li><strong className="text-white">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                  <li><strong className="text-white">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                  <li><strong className="text-white">Service</strong> refers to the Application.</li>
                  <li><strong className="text-white">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                  <li><strong className="text-white">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                  <li><strong className="text-white">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>

                <h3 className="text-xl font-semibold text-white mt-8 mb-4">Collecting and Using Your Personal Data</h3>
                
                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Types of Data Collected</h4>
                
                <h5 className="text-md font-semibold text-white mt-4 mb-2">Personal Data</h5>
                <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                
                <ul className="list-disc pl-6 space-y-1 mt-3">
                  <li>Mobile number</li>
                  <li>First name and last name</li>
                  <li>Usage Data</li>
                </ul>

                <h5 className="text-md font-semibold text-white mt-4 mb-2">Usage Data</h5>
                <p>Usage Data is collected automatically when using the Service.</p>
                <p className="mt-2">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <p className="mt-2">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Use of Your Personal Data</h4>
                <p>The Company may use Personal Data for the following purposes:</p>
                
                <ul className="list-disc pl-6 space-y-2 mt-3">
                  <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                  <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
                  <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                  <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                  <li>To provide You with news, special offers and general information about other goods, services and events which we offer.</li>
                  <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                  <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                  <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
                </ul>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Retention of Your Personal Data</h4>
                <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Transfer of Your Personal Data</h4>
                <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Delete Your Personal Data</h4>
                <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
                <p className="mt-2">You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Disclosure of Your Personal Data</h4>
                
                <h5 className="text-md font-semibold text-white mt-4 mb-2">Business Transactions</h5>
                <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

                <h5 className="text-md font-semibold text-white mt-4 mb-2">Law enforcement</h5>
                <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Security of Your Personal Data</h4>
                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Children's Privacy</h4>
                <p>Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Links to Other Websites</h4>
                <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Changes to this Privacy Policy</h4>
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <p className="mt-2">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>

                <h4 className="text-lg font-semibold text-white mt-6 mb-3">Contact Us</h4>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul className="list-disc pl-6 space-y-1 mt-3">
                  <li>By email: support@rajkalyanmatka.com</li>
                  <li>By phone: +91-XXXXXXXXXX</li>
                  <li>By WhatsApp: +91-XXXXXXXXXX</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default PrivacyPolicy 